language: node_js
node_js:
  - "10.16.0"
cache:
  - npm
install:
  - npm install
  - npm install -g gulp-cli
script:
  - cd ui && npm install && gulp bundle
  - node_modules/@antora/cli/bin/antora site.yml
deploy:
  local_dir: build/site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: gh-pages
  on:
    branch: antora-test
